language: python

python:
- 3.4
- 3.5
- 3.6

install:
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- conda-mirror -h
- coverage run run_tests.py
- coverage report -m

after_success:
- codecov
