language: python

python:
- 3.4
- 3.5
- 3.6

install:
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- conda-mirror -h
- pytest --cov=conda_mirror --cov-report term-missing -v test/test_conda_mirror.py -s

after_success:
- codecov
