language: python

python:
- 3.4
- 3.5
- 3.6

install:
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- conda-mirror -h
- echo "Running test in serial mode."
- coverage run run_tests.py
- export CONDA_MIRROR_NUM_THREADS=2
- echo "Running test in concurrent mode with" $CONDA_MIRROR_NUM_THREADS "threads."
- coverage run run_tests.py
- coverage report -m

after_success:
- codecov
